### ISSUE TITLE
Boolean variables parses as string

### ISSUE THREAD

**Issue by barbushin** [vlucas/phpdotenv#129] opened 2015-10-28 11:23 UTC
In .env
```
debug=true
```

In PHP
```
$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();
var_dump(getenv('debug'));
```

Output:
```
string 'false' (length=5)
```

PHP 5.6, dotenv v2.0.1, Windows 10x64

**Comment by tuupola** [comment] 2015-10-28 12:19
Environment variables are case sensitive.

```php
var_dump(getenv('DEBUG'));
```

Yields

```
string(4) "true"
```

**Comment by barbushin** [comment] 2015-10-28 12:20
So what? It's still `string(4)`, not boolean.

**Comment by tuupola** [comment] 2015-10-28 12:26
Point is, your example `.env` and output do not match. In any case there is [discussion about boolean values](https://github.com/vlucas/phpdotenv/issues/104).

**Comment by barbushin** [comment] 2015-10-28 15:28
It was just a typ :D In my project code is correct, without type. Otherwise var_dump dieplayed NULL.

**Comment by GrahamCampbell** [comment] 2015-10-28 15:47
Duplicate of https://github.com/vlucas/phpdotenv/issues/104.

**Closed by GrahamCampbell** 2015-10-28 15:46 UTC
