### ISSUE TITLE
Partial loading of .env file on production server

### ISSUE THREAD

**Issue by systemist** [vlucas/phpdotenv#266] opened 2018-04-21 13:07 UTC
I know this library isn't meant to be used in production, however I've stumbled upon an error that I find very strange and I would like to understand what's going on.

On a production server, when dotenv `load` method was called many times per second, "sometimes" not all varibles listed in the .env file were loaded. I would get this issue around 1 time out of 1k-10k requests, I didn't measure exactly, but its a relatively small percentage of all requests. Out of ~20 defined vars, I would sometimes get 0 loaded, sometimes half of them, sometimes just one var missing, etc. Like setting environment vars would be at race conditions with the rest of the script.

On a development machine which doesn't have traffic I was unable to reproduce this issue.

Moving environment setup to apache virtual host config fixed the problem immediately.

The server is apache 2.4 with php 7 using mod_php.

I tried Symfony dotenv component and it had the same problem.

Since both symfony and phpdotenv have the same problem, I am guessing this is probably a bug in apache/php. 

Is this a known issue?

Is it safe to use this library for CLI / cron scripts in production?

**Comment by tomzx** [comment] 2018-04-21 17:51
Looks like a duplicate of #248.

**Comment by systemist** [comment] 2018-04-21 18:14
Yes, opcache is on in both production and development.

I've read the other issue, but it is still unclear what exactly causes this behavior?

**Comment by systemist** [comment] 2018-04-21 20:09
Disabling opcache did not solve the problem.

I also noticed that values returned from `getenv()` call and $_ENV global can be different. Sometimes getenv() returns false and $_ENV has a proper value, sometimes they are both unset.

**Comment by systemist** [comment] 2018-04-21 20:36
My code relies on `getenv()` everywhere. Here is how I know they are not loaded or partially loaded.

.env:

    APP_ENV="prod"
    ... other vars

script code:

	if ( ! getenv('APP_ENV')) {
		$dotenv = new \Symfony\Component\Dotenv\Dotenv();
		$dotenv->load(__DIR__ . '/../../.env');
	}

and later:

    if (getenv('SOME_VAR_DEFINED_IN_DOTENV') === false) {
         // log return values of getenv() and $_ENV
         // the contents of getenv() and $_ENV vary randomly here
    }

**Comment by systemist** [comment] 2018-04-21 21:10
I have modified Loader.php as suggested and still get the error.

Also got one interesting scenario:

Script code:

    if (!getenv('DATA_DIR')) { // <--- Condition evaluated to true here (DATA_DIR must have been empty)
      $g = print_r(getenv(), true); // <--- DATA_DIR is already defined at this point
      $e = print_r($_ENV, true);
      throw new Exception('Undefined data dir: ' . $g . $e);
    }

Dumped exception data:

    2018-04-21 20:55:10 [ERROR] Exception: Undefined data dir: Array
    (
        [TERM] => xterm
        [SYSTEMCTL_SKIP_REDIRECT] =>
        [LD_LIBRARY_PATH] => /usr/local/apache2/lib
        [PATH] => /sbin:/usr/sbin:/bin:/usr/bin
        [PWD] => /
        [SHLVL] => 1
        [SYSTEMCTL_IGNORE_DEPENDENCIES] =>
        [_] => /usr/local/sbin/httpd
        [APP_ENV] => prod
        [AMAZON_SES_USERNAME] => ***
        [AMAZON_SES_PASSWORD] => ***
        [AMAZON_SES_HOSTNAME] => ***
        [DKIM_SELECTOR] => 20170916
        [SENTRY_DSN] => ***
        [LOCAL_JQUERY] => 0
        [DATA_DIR] => /webdata/
    )
    Array
    (
        [TERM] => xterm
        [SYSTEMCTL_SKIP_REDIRECT] =>
        [LD_LIBRARY_PATH] => /usr/local/apache2/lib
        [PATH] => /sbin:/usr/sbin:/bin:/usr/bin
        [PWD] => /
        [SHLVL] => 1
        [SYSTEMCTL_IGNORE_DEPENDENCIES] =>
        [_] => /usr/local/sbin/httpd
        [APP_ENV] => prod
        [AMAZON_SES_USERNAME] => ***
        [AMAZON_SES_PASSWORD] => ***
        [AMAZON_SES_HOSTNAME] => ***
        [DKIM_SELECTOR] => 20170916
        [SENTRY_DSN] => ***
        [LOCAL_JQUERY] => 0
        [DATA_DIR] => /webdata/
    )

Notice how the script checks for existance of `DATA_DIR` variable. At the moment of check, `DATA_DIR` is undefined, while in the exception dump (generated next line) it is already defined.

**Comment by tomzx** [comment] 2018-04-21 23:15
Can you specify which exact version of PHP you are using?

**Comment by GrahamCampbell** [comment] 2019-01-02 17:25
See https://github.com/vlucas/phpdotenv/issues/219 for why this is happening.

**Closed** 2019-01-02 17:24 UTC

**Comment by GrahamCampbell** [comment] 2019-01-26 17:39
I think it's likely the following example will work in a multithreaded environment. This avoids using the adapter that would have called `putenv` and `getenv`, which are not threadsafe.

```php
<?php

use Dotenv\Environment\Adapter\EnvConstAdapter;
use Dotenv\Environment\Adapter\ServerConstAdapter;
use Dotenv\Environment\DotenvFactory;
use Dotenv\Dotenv;

$factory = new DotenvFactory([new EnvConstAdapter(), new ServerConstAdapter()]);

Dotenv::create($path, null, $factory)->load();
```
