### ISSUE TITLE
env file not always loading

### ISSUE THREAD

**Issue by RickKukiela** [vlucas/phpdotenv#248] opened 2017-11-13 18:45 UTC
I'm using craft3 beta which uses this package to load the config data. 

On my main computer its a core i7 (2016 model) with 24gb RAM and a M.2 SSD etc. I do not have any problems loading .env every time.

Our other PC has a a regular SSD, Core2 Quad 2.4ghz  and 8gb of RAM

On the other computer every once in a while the .env data fails to load, which causes craft3 to crash due to the database driver value being empty because .env did not load. 

Simply refreshing the page causes the error to go away for a while but it always comes back.

An exact replication of that environment does not bug on my PC at all. Aside from the speed difference, the only other difference is the problem computer is running PHP 7.1.3 and I'm running PHP 7.1.0

**Comment by kalvn** [comment] 2018-01-09 16:06
Same here, for some reason, once in a while the file is not read and I get message `One or more environment variables failed assertions: ENV is missing.` (ENV is one of the parameter).

**Comment by tomzx** [comment] 2018-01-12 21:21
@RickKukiela What operating system are you using? What is your environment like (apache/nginx, php loaded as module/php-fpm)?

**Comment by RickKukiela** [comment] 2018-01-12 22:36
@tomzx Windows 10, easyphp devserver (no docker / virtual machine setup), mariadb running locally, php 7.1

I have this same setup on multiple machines and only the old slow machine exhibits this behavior.

**Comment by kalvn** [comment] 2018-01-12 22:53
On my side: Solaris, PHP 5.6 Apache 2.4 with mod_php.

**Comment by requtize** [comment] 2018-01-19 11:44
This is caused by putenv() and getenv() functions in PHP. This library uses it to define if env variable already exists and if not - do nothing. I tested it, and I realize that $_ENV variable was filled with values from .env file, but getenv() function always return null.

Maybe there will be a good idea, to add some configuration, to define if the variables from the .env file should be placed only in $_ENV variable, or both in $_ENV and putenv(). And with getting values the same. This should fix the problem, and wasn't cause backwards compatibility.

Sure, You can overwrite values, but sometimes we don't want to do this, and described solution can works.

**Comment by dgrosso** [comment] 2018-02-15 15:50
I'm experiencing the same issue when I run multiple concurrent ajax resquests. 

My .env file has 15 lines (only 6 of them are variables) but in some of the concurrent requests, my `$_ENV` is empty after `$dotenv->load()`. If I make a `var_dump($dotenv->load())`, it **always** displays the 15 lines of the .env file, so I think it must be something with the parsing logic. Any ideas?

I'm running on Apache 2.4.29 with PHP 5.6.33
SO: Arch Linux x86_64 4.14.15-1
PC: i5 (7th gen), 8gb RAM, SSD

**Comment by requtize** [comment] 2018-02-15 16:13
I create my own function _env()_ (like PHP's built-in _getenv()_), and in this function I use **only** _$_ENV_ global variable to get values. Now, I don't have any problems, but this thing should be fixed in the Library.

**Comment by AeonFr** [comment] 2018-08-13 08:36
Believe it or not, using $_ENV didn't do the trick for me. It was weird because only in one API endpoint the env file wasn't loading, and in all the other endpoints it was. Probably the error triggers when a lot of requests go to the server at the same time.

I was able to solve it by recursively trying to load the env file.

```
function loadEnvRecursive(){
    $dotenv = new Dotenv\Dotenv(__DIR__);
    $dotenv->load();
    if (!isset($_ENV['ROOT_FOLDER'])) // checks a variable that should be loaded
    {
        return loadEnvRecursive(); // if not set, retry ad infinitum
    }
}

loadEnvRecursive();
```

**Comment by GrahamCampbell** [comment] 2019-01-02 16:02
Duplicate of https://github.com/vlucas/phpdotenv/issues/219.

**Closed** 2019-01-02 16:02 UTC

**Comment by sridesmet** [comment] 2019-01-02 16:03
Putenv and Getenv are not thread-safe. This is probably the cause of your issue.

What happens is the following:
1st request: variables are not there -> load
2nd request: variables are there -> do not load
1st request: ends, cleans up variables
2nd request: use variable -> does not exist anymore, cleaned up by 1st request

**Comment by GrahamCampbell** [comment] 2019-01-02 16:04
Yes, this library cannot be used in a multi-threaded environment. The issue is well-described in the link I posted. :)

**Comment by GrahamCampbell** [comment] 2019-01-26 17:39
I think it's likely the following example will work in a multithreaded environment. This avoids using the adapter that would have called `putenv` and `getenv`, which are not threadsafe.

```php
<?php

use Dotenv\Environment\Adapter\EnvConstAdapter;
use Dotenv\Environment\Adapter\ServerConstAdapter;
use Dotenv\Environment\DotenvFactory;
use Dotenv\Dotenv;

$factory = new DotenvFactory([new EnvConstAdapter(), new ServerConstAdapter()]);

Dotenv::create($path, null, $factory)->load();
```

**Comment by tomasvanrijsse** [comment] 2019-03-12 09:42
I've tried this solution and it did solve the issue.
I overlooked the details of the answer however and other packages stopped working because they relied on `getenv`.
Since we where only experiencing this issue on Windows we simply only applied this custom list of adapters on Windows only.

**Comment by GrahamCampbell** [comment] 2019-03-12 17:27
> I overlooked the details of the answer however and other packages stopped working because they relied on getenv.

There's no work around for packages that use a function that isn't threadsafe. They should instead update their code to be threadsafe. The `$_SEVER` variable behaves most closely to `getenv`.
