### ISSUE TITLE
Trimming of string literals

### ISSUE THREAD

**Issue by pawelabrams** [vlucas/phpdotenv#162] opened 2016-02-17 21:27 UTC
Due to double trimming of values at Loader::sanitiseVariableValue, string literals are being trimmed; that is, `HERP = "     please don't"` is forced to be `please don't`.

It didn't cause problems as of yet, because everyone is accustomed to space and tabs being unsafe characters, but no one should have to rely on this behaviour.

**Comment by pawelabrams** [comment] 2016-02-17 21:28
Cont'd: github's inline code replaces multiple spaces with one. How accurate.

**Comment by rquadling** [comment] 2016-02-18 09:40
I disagree. A string literal is a string literal. If it has been quoted, then I have perfectly described my intent and expect it to be respected. Arbitrarily removing my content is certainly a bug.

**Comment by tuupola** [comment] 2016-04-25 11:06
Since this was closed does this mean trimming of string literals are expected behaviour. To me it feels like a bug.

**Comment by rquadling** [comment] 2016-04-25 12:24
@tuupola I agree, if double trimming is going to happen, completely no need to wrap the content in quotes either.

**Comment by GrahamCampbell** [comment] 2016-05-06 09:52
Does https://github.com/vlucas/phpdotenv/pull/179 do what you want?

**Comment by GrahamCampbell** [comment] 2016-05-06 09:53
> no need to wrap the content in quotes either.

Actually, we do still require that. If you have `foo bar` as the variable, you need quotes due to the whitespace inside.

**Comment by GrahamCampbell** [comment] 2016-06-14 14:10
Closing because php trims the variables anyway when we pass them in.

**Closed** 2016-06-14 14:10 UTC

**Comment by pantaoran** [comment] 2016-06-17 08:03
I'm having problems with this now. My variable needs a whitespace at the end, because it's a prefix that will later be concatenated with something else at runtime. That concatenation happens inside another library that I use, and I don't want to touch their code, otherwise I won't be able to update the lib.

How do I get this to work now? Any possible workaround?

**Comment by barryatswisnl** [comment] 2016-10-11 14:04
It seems to me that all values (including quoted ones) are trimmed when loading them. Take a look at line 232 of Loader.php: 

`return array($name, trim($value));`

What is the rationale behind this and what is a possible workaround?
